### ISSUE TITLE
Changing order of fields?

### ISSUE THREAD

**Issue by saurabhnanda** [Happstack/reform-happstack#1]
Please excuse me if this questions sounds stupid, I'm still trying to wrap my head around form layout (i.e. HTML generation) in digestive-functors and reform-happstack.

Going by this example from the Happstack book, is it necessary to have the fields visually laid out in the same order as the underlying record type?

```
postForm :: SimpleForm Message
postForm =
  Message
   <$> labelText "name:"             ++> inputText ""      <++ br
   <*> labelText "title: "           ++> inputText ""      <++ br
   <*> (labelText "message:" <++ br) ++> textarea 80 40 "" <++ br
   <*  inputSubmit "post"
```

**Comment by stepcut** [comment]
Yes and no. In your code yes.

If you wanted a different order you could provide explicit arguments to the `Message` constructor like this:

```
postForm :: SimpleForm Message
postForm =
  (\n t m p -> Message n t m p)
   <$> labelText "name:"             ++> inputText ""      <++ br
   <*> labelText "title: "           ++> inputText ""      <++ br
   <*> (labelText "message:" <++ br) ++> textarea 80 40 "" <++ br
   <*  inputSubmit "post"
```
Now if we swap the order of some fields, we just swap the order of the arguments:
```
postForm :: SimpleForm Message
postForm =
  (\n m t p -> Message n t m p)
   <$> labelText "name:"             ++> inputText ""      <++ br
   <*> (labelText "message:" <++ br) ++> textarea 80 40 "" <++ br
   <*> labelText "title: "           ++> inputText ""      <++ br
   <*  inputSubmit "post"
```

I have not checked that this code compiles, but I think it should.
